# ABOUTME: Post-processing script that widens text boxes in PPTX files by ~5% rightward.
# ABOUTME: Fixes text clipping from Marp→PDF→PPTX pipeline where LibreOffice creates tight text frames.

# /// script
# requires-python = ">=3.10"
# dependencies = ["python-pptx"]
# ///

"""
Widen text frames in PPTX files generated by Marp's --pptx-editable pipeline.

Usage:
    uv run scripts/fix-pptx-margins.py <file.pptx>
    uv run scripts/fix-pptx-margins.py <directory>  (processes all .pptx files)
"""

import sys
from pathlib import Path

from pptx import Presentation
from pptx.util import Inches

EXPAND_FACTOR = 0.05  # 5% wider

# Standard 16:9 Marp slide dimensions
SLIDE_WIDTH = Inches(13.333)
SLIDE_HEIGHT = Inches(7.5)


def fix_pptx(path: Path) -> int:
    """Widen all text frames in a PPTX file by EXPAND_FACTOR. Returns count of shapes modified."""
    prs = Presentation(str(path))
    count = 0

    for slide in prs.slides:
        for shape in slide.shapes:
            if not shape.has_text_frame:
                continue

            extra = int(shape.width * EXPAND_FACTOR)
            new_width = shape.width + extra

            # Clamp so shape doesn't exceed right edge of slide
            if shape.left + new_width > SLIDE_WIDTH:
                new_width = SLIDE_WIDTH - shape.left

            shape.width = new_width
            count += 1

    prs.save(str(path))
    return count


def main():
    if len(sys.argv) < 2:
        print(f"Usage: {sys.argv[0]} <file.pptx | directory>", file=sys.stderr)
        sys.exit(1)

    target = Path(sys.argv[1])

    if target.is_dir():
        files = sorted(target.glob("*.pptx"))
    elif target.is_file() and target.suffix == ".pptx":
        files = [target]
    else:
        print(f"ERROR: {target} is not a .pptx file or directory", file=sys.stderr)
        sys.exit(1)

    if not files:
        print(f"No .pptx files found in {target}", file=sys.stderr)
        sys.exit(0)

    for f in files:
        count = fix_pptx(f)
        print(f"  FIX:  {f} ({count} text frames widened by {int(EXPAND_FACTOR * 100)}%)")


if __name__ == "__main__":
    main()
